title: "Jason Schmidberger"
description: "Data science portfolio and blog"
url: "https://jwschmidberger.github.io"
baseurl: ""
permalink: /blog/:year/:month/:day/:title/

author:
  name: "Jason Schmidberger"
  email: "jason.schmidberger@gmail.com"
  github: "jwschmidberger"
  linkedin: "jwschmidberger"
  location: "Sydney, Australia"

markdown: kramdown
highlighter: rouge
timezone: Australia/Sydney

remote_theme: daviddarnes/alembic

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
    values:
      layout: page

sass:
  sass_dir: _sass
  style: compressed

social:
  github: https://github.com/jwschmidberger
  linkedin: https://www.linkedin.com/in/jwschmidberger/
  email: mailto:jason.schmidberger@gmail.com

skin: forest

exclude:
  - node_modules
  - vendor
  - README.md
  - Gemfile.lock
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - package.json
  - yarn.lock
  - pdfs
  - reveal.js
  - ntbooks
