title: "Jason Schmidberger"
description: "Data science portfolio and blog"
url: "https://jwschmidberger.github.io"
baseurl: ""
permalink: /blog/:year/:month/:day/:title/

author:
  name: "Jason Schmidberger"
  email: "jason.schmidberger@gmail.com"
  github: "jwschmidberger"
  linkedin: "jwschmidberger"
  location: "Sydney, Australia"

markdown: kramdown
highlighter: rouge
timezone: Australia/Sydney

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
      nav_order: 2
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules
  - vendor
  - README.md
  - Gemfile.lock
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - package.json
  - yarn.lock
  - pdfs
  - reveal.js
  - ntbooks
